In [1]:
import torch
import numpy as np

In [3]:
numpy_tensor = np.random.randn(10,20)
print(numpy_tensor)

[[-0.083468    0.8461055   2.01481512 -0.86019954  0.76324429  0.14131644
  -0.06803275 -0.56301422 -0.7459156   0.44127388  1.22573458  0.05915903
  -0.36997219  1.50206551 -0.41513822 -0.61791897  1.32205938  0.22123426
  -0.3819525   1.51818716]
 [ 0.32844007  1.35775848  1.293389    1.12271049 -0.64875048 -1.69902919
  -0.82641031  0.53365654 -1.23708619  0.46984492  2.22391763  1.27909974
   0.89938878 -0.37142159 -0.17455635  0.68603107 -1.27673062  0.48475429
   1.03214067 -0.13593122]
 [-0.00996292  1.03772716  0.04038206 -0.40296852  0.87724177  1.0635165
   1.69528737 -0.16215874  1.37864492 -0.09715551 -0.11198136  0.05049977
  -0.00935499 -0.5742411   0.11337189 -0.82879811  0.4808113  -2.27411008
   1.48903458  0.41312729]
 [-1.61060529  0.31383363  2.12023621 -1.67273885  0.37760096 -0.9285172
   0.93782154  0.26445134 -0.67529663  0.37507568  0.97961717 -0.20547234
   0.08551471  0.1461559   0.18198137 -0.41214544  0.56940285  2.01796693
   1.77261447 -0.89202825]
 [-1.1

In [4]:
pytorch_tensor1 = torch.Tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)
print(pytorch_tensor1)
print(pytorch_tensor2)

tensor([[-0.0835,  0.8461,  2.0148, -0.8602,  0.7632,  0.1413, -0.0680, -0.5630,
         -0.7459,  0.4413,  1.2257,  0.0592, -0.3700,  1.5021, -0.4151, -0.6179,
          1.3221,  0.2212, -0.3820,  1.5182],
        [ 0.3284,  1.3578,  1.2934,  1.1227, -0.6488, -1.6990, -0.8264,  0.5337,
         -1.2371,  0.4698,  2.2239,  1.2791,  0.8994, -0.3714, -0.1746,  0.6860,
         -1.2767,  0.4848,  1.0321, -0.1359],
        [-0.0100,  1.0377,  0.0404, -0.4030,  0.8772,  1.0635,  1.6953, -0.1622,
          1.3786, -0.0972, -0.1120,  0.0505, -0.0094, -0.5742,  0.1134, -0.8288,
          0.4808, -2.2741,  1.4890,  0.4131],
        [-1.6106,  0.3138,  2.1202, -1.6727,  0.3776, -0.9285,  0.9378,  0.2645,
         -0.6753,  0.3751,  0.9796, -0.2055,  0.0855,  0.1462,  0.1820, -0.4121,
          0.5694,  2.0180,  1.7726, -0.8920],
        [-1.1230, -0.6705, -0.7508, -0.7860,  0.0437, -0.4436, -1.5356,  0.5534,
         -0.6080,  0.6436,  0.2420,  0.0975, -0.2605, -0.3211,  0.9918, -0.1346,
      

In [5]:
numpy_array = pytorch_tensor1.numpy()
#numpy_array = pytorch_tensor1.cpu().numpy

In [6]:
dtype = torch.cuda.FloatTensor
gpu_tensor = torch.randn(10,20).type(dtype)

gpu_tensor = torch.randn(10,20).cuda(0)
gpu_tensor = torch.randn(10,20).cuda(1)

RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

In [7]:
cpu_tensor = gpu_tensor.cpu()

NameError: name 'gpu_tensor' is not defined

In [9]:
print(pytorch_tensor1.shape)
print(pytorch_tensor1.size())
print(pytorch_tensor1.type())
print(pytorch_tensor1.dim())
print(pytorch_tensor1.numel())

torch.Size([10, 20])
torch.Size([10, 20])
torch.FloatTensor
2
200


In [15]:
extensor = torch.randn(3,2).type(torch.float64)
exnum = extensor.numpy()
print(exnum.size)
print(exnum.dtype)

6
float64


In [18]:
x = torch.ones(2,2)
print(x)
print(x.type())
x = x.long()
print(x)
print(x.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor
tensor([[1, 1],
        [1, 1]])
torch.LongTensor


In [21]:
x = torch.randn(4,3)
print(x)
max_value, max_idx = torch.max(x,dim=1)
print(max_value)
print(max_idx)
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([[-0.1498, -0.9257,  0.4755],
        [ 0.6373, -0.6279, -0.0356],
        [ 0.1847, -1.4123, -1.8298],
        [ 0.1446,  0.2520,  0.2084]])
tensor([0.4755, 0.6373, 0.1847, 0.2520])
tensor([2, 0, 0, 1])


In [22]:
print(x.shape)
x = x.unsqueeze(0)
print(x.shape)

x = x.unsqueeze(1)
print(x.shape)

x = x.squeeze()
print(x.shape)

torch.Size([4, 3])
torch.Size([1, 4, 3])
torch.Size([1, 1, 4, 3])
torch.Size([4, 3])


In [23]:
x = torch.randn(3,4,5)
print(x.shape)
print(x)

x = x.permute(1,0,2)
print(x.shape)
print(x)

x = x.transpose(0,2)
print(x.shape)
print(x)

torch.Size([3, 4, 5])
tensor([[[-0.3462,  2.8270,  0.3841,  0.4083, -0.2538],
         [ 0.3054, -0.4435,  0.0253,  0.8146, -0.3237],
         [-0.1145, -2.2570,  0.9820, -1.1142,  0.7558],
         [-0.9290,  0.2865, -2.3827, -1.5568, -1.5452]],

        [[-0.3760,  0.1415, -1.5967,  1.2326,  0.2184],
         [-0.3739,  2.0240, -0.8485,  1.4438,  1.4150],
         [-0.3809,  1.4008, -0.5829,  1.7134, -0.6310],
         [ 0.0556, -2.1446, -1.2157, -0.2588, -0.9825]],

        [[ 0.2802,  0.0282, -0.9078, -0.4914, -0.3226],
         [-1.3922, -0.1659, -1.1172,  0.1645,  0.0420],
         [-0.3107, -1.1054,  1.8818,  1.1796, -0.5975],
         [ 1.1332, -1.3330,  1.5681, -0.7381, -1.5442]]])
torch.Size([4, 3, 5])
tensor([[[-0.3462,  2.8270,  0.3841,  0.4083, -0.2538],
         [-0.3760,  0.1415, -1.5967,  1.2326,  0.2184],
         [ 0.2802,  0.0282, -0.9078, -0.4914, -0.3226]],

        [[ 0.3054, -0.4435,  0.0253,  0.8146, -0.3237],
         [-0.3739,  2.0240, -0.8485,  1.4438,  1.415

In [24]:
x = torch.randn(3,4,5)
print(x.shape)

x = x.view(-1,5)
print(x.shape)

x = x.view(3,20)
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


In [25]:
x = torch.randn(3,4)
y = torch.randn(3,4)
z = x + y
print(z)

tensor([[ 1.0373,  1.6782,  0.5450,  1.3289],
        [ 1.5488, -0.5806, -1.9223, -1.8061],
        [ 1.1816, -0.3267, -1.0400,  0.9854]])


In [27]:
x = torch.ones(3,3)
x.unsqueeze_(0)
print(x.shape)
x.transpose_(1,0)
print(x.shape)

torch.Size([1, 3, 3])
torch.Size([3, 1, 3])


In [28]:
x = torch.ones(3,3)
y = torch.ones(3,3)

print(x)
x.add_(y)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [32]:
x = torch.ones(4,4).float()
print(x)
x[1:3,1:3] = 2
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 2., 2., 1.],
        [1., 2., 2., 1.],
        [1., 1., 1., 1.]])
